language: c # No such language as ocaml for Travis.
services:
  - docker
before_install:
  - docker build -t planalyzer .
script:
  - docker run -t planalyzer ./build_and_test.sh
git:
  submodules: true
